/** Agent definitions: system prompt builder and Ollama tool schemas for multi-agent routing. */

export type AgentSystemInfo = {
  cpu_name: string
  cpu_cores: number
  total_ram_gb: number
  has_gpu: boolean
  gpu_name: string
  gpu_vram_gb: number
  backend: string
  os?: string
  unified_memory?: boolean
}

export type AgentModelInfo = {
  name: string
  parameter_count: string
  fit_level: string
  memory_required_gb: number
  use_case: string
  context_length?: number
  run_mode?: string
  provider?: string
  is_moe?: boolean
}

export interface AgentDefinition {
  id: string
  name: string
  description: string
  /** Build system prompt. Receives (baseContext, system, models, contextLength, attachedFileNames). */
  buildSystemPrompt: (
    baseContext: string,
    system: AgentSystemInfo | null,
    models: AgentModelInfo[],
    contextLength: number,
    attachedFileNames: string[]
  ) => string
  /** Ollama tool schemas (subset of tools this agent can use). */
  tools: Array<{
    type: 'function'
    function: {
      name: string
      description: string
      parameters: {
        type: 'object'
        properties: Record<string, { type: string; description: string }>
        required?: string[]
      }
    }
  }>
}

/** Rich ForeLLM + models knowledge so the agent stays updated on commands, fit, run modes, and the app. */
export const forellmKnowledge = `
## ForeLLM overview
ForeLLM is a Rust CLI/TUI/GUI tool that matches LLM models to local hardware (RAM, CPU, GPU). It detects system specs, loads a model database (data/hf_models.json, embedded at compile time), scores each model's fit, and presents results in the TUI, GUI, or classic table (--cli). The GUI includes this Agent Fore chat and uses Ollama for local inference; ForeLLM itself does not run the models—it recommends which models fit the machine.

## CLI commands
- forellm system — Show detected hardware (CPU, RAM, GPU, backend, OS).
- forellm list — List all models in the database (optionally with fit).
- forellm fit — Show models with fit analysis for current or overridden hardware. Use --perfect, --good, --marginal, --too-tight to filter; -n N to limit; --json for machine-readable output.
- forellm search <query> — Search models by name or provider.
- forellm download <model> — Download a model (delegates to ollama or backend). Options: --quant, --list.
- forellm recommend — Get recommendations; options: --limit, --use-case, --min-fit.
- forellm info <model> — Detailed info for one model.
- forellm plan <model> — Planning output (--json, --context, --quant, --target-tps).
- forellm --cli — Use classic table output instead of TUI.

## Fit levels (ordered best to worst)
Perfect > Good > Marginal > TooTight. Fit is VRAM-first: GPU inference with enough VRAM is ideal; CPU offload or CPU-only are fallbacks. Do not add new fit levels without updating ranking.

## Run modes
- Gpu — Model runs on GPU (VRAM).
- CpuOffload — Part on GPU, part on system RAM (when VRAM is insufficient).
- CpuOnly — Full inference in system RAM (no GPU or not enough VRAM).
On Apple Silicon (unified memory), VRAM and system RAM are the same pool; CpuOffload is skipped. min_vram_gb = VRAM needed for GPU; min_ram_gb = system RAM for CPU-only (same weights, different pool).

## Model database
- Source: data/hf_models.json. Generated by scripts/scrape_hf_models.py (Python stdlib, no pip). Do not edit JSON by hand; regenerate with: python3 scripts/scrape_hf_models.py.
- Schema: name, provider, parameter_count, min_ram_gb, recommended_ram_gb, min_vram_gb, quantization, context_length, use_case.
- Memory: Q4_K_M default (0.5 bytes/param). RAM formula: params * 0.5 / 1024^3 * 1.2 overhead; VRAM: * 1.1 activation. Recommended RAM: model_size * 2.0.
- Adding a model: add HuggingFace repo ID to TARGET_MODELS in scrape_hf_models.py; for gated models add fallback to FALLBACK; run scraper; cargo build.

## Quantization (GGUF-style)
Q2_K, Q3_K_M, Q4_K_M (default), Q5_K_M, Q6_K, Q8_0, FP16. Lower bits = smaller, faster, less quality.

## Ollama (GUI and CLI agent)
The ForeLLM GUI uses Ollama for local inference in the Agent Fore tab. A CLI version of Agent Fore runs in the terminal: from the forellm-gui directory run: npm run agent (or npx tsx cli/agent-cli.ts). Options: --model <ollama-model>, --agent general|data|web|coding, --file <path> (repeat to attach files). Same agents and tools; run_command prompts for Allow [y/N] in the terminal. Suggest "ollama run <model>" to run a model; forellm download <model> can help prepare.

## Common tasks
cargo build / cargo run; cargo run -- --cli for table; forellm system | fit | list | search "llama"; refresh DB: python3 scripts/scrape_hf_models.py && cargo build.
`.trim()

export const baseForellmContext = `
You are Agent Fore, an expert AI assistant inside the ForeLLM app. You have access to the current machine's specs and the ForeLLM model database. Use the following knowledge to give accurate, up-to-date answers about ForeLLM, models, fit, and commands. Be concise and helpful.

${forellmKnowledge}
`.trim()

export const AGENTS: AgentDefinition[] = [
  {
    id: 'general',
    name: 'General Assistant',
    description: 'ForeLLM context, hardware, and general Q&A',
    buildSystemPrompt: (baseContext, system, models, contextLength, attachedFileNames) => {
      const lines = [baseContext]
      if (system) {
        lines.push(
          '',
          '## Current system',
          `CPU: ${system.cpu_name}, ${system.cpu_cores} cores. RAM: ${system.total_ram_gb} GB.`,
          system.has_gpu ? `GPU: ${system.gpu_name}, ${system.gpu_vram_gb} GB VRAM.` : 'GPU: none.',
          `Backend: ${system.backend}.${system.os ? ` OS: ${system.os}.` : ''}`
        )
      }
      lines.push('', `Context length (user setting): ${contextLength}.`)
      if (models.length) {
        lines.push('', '## Models in database (sample; fit and run_mode are for current hardware)')
        models.slice(0, 40).forEach((m) => {
          const ctx = m.context_length != null ? ` ctx=${m.context_length}` : ''
          const mode = m.run_mode ? ` ${m.run_mode}` : ''
          const moe = m.is_moe ? ' MoE' : ''
          lines.push(`- ${m.name}: ${m.parameter_count}${moe}, fit=${m.fit_level}, ${m.memory_required_gb.toFixed(1)} GB${ctx}${mode}, use: ${m.use_case}`)
        })
        if (models.length > 40) lines.push(`- ... and ${models.length - 40} more.`)
      }
      if (attachedFileNames.length) lines.push('', `User has attached: ${attachedFileNames.join(', ')}. Use read_document with the file_id to read them (works for JSON, TXT, CSV, etc.). If read_document fails, use run_command to run a terminal command to read the file (e.g. type path on Windows, cat path on Unix); the user will be asked to confirm.`)
      lines.push('', 'To ask the user a question with reply buttons, end your message with a line: BUTTONS: Yes, No  or  BUTTONS: Option1, Option2')
      return lines.join('\n')
    },
    tools: [
      {
        type: 'function',
        function: {
          name: 'read_document',
          description: 'Read the full text content of an uploaded file by its file_id (JSON, TXT, CSV, etc.).',
          parameters: {
            type: 'object',
            properties: { file_id: { type: 'string', description: 'The file ID returned when the user uploaded the file.' } },
            required: ['file_id']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'run_command',
          description: 'Run a terminal command (e.g. to read a file if read_document failed). User must confirm before the command runs. Use for reading files: type path (Windows) or cat path (Unix).',
          parameters: {
            type: 'object',
            properties: { command: { type: 'string', description: 'The shell command to run (e.g. type C:\\path\\file.json or cat /path/file.json).' } },
            required: ['command']
          }
        }
      }
    ]
  },
  {
    id: 'data',
    name: 'Data Analyst',
    description: 'Analyze data, CSVs, and run Python',
    buildSystemPrompt: (baseContext, system, models, contextLength, attachedFileNames) => {
      const lines = [
        baseContext,
        '',
        'You are the Data Analyst agent. Focus on data analysis: CSVs, statistics, charts, and Python (pandas, matplotlib).',
        'Use read_document to load uploaded files and execute_python to run code. Prefer small, focused code snippets. After every tool run, always reply with a short follow-up (result or next step)—do not leave the user with no message.'
      ]
      if (system) lines.push('', `System: ${system.cpu_name}, ${system.cpu_cores} cores, ${system.total_ram_gb} GB RAM.`)
      if (attachedFileNames.length) lines.push('', `Attached files: ${attachedFileNames.join(', ')}. Use read_document(file_id) to read them (JSON, CSV, TXT). If that fails, use run_command to read via terminal; user will confirm.`)
      lines.push('', 'End a message with BUTTONS: Yes, No (or other labels) to show reply buttons.')
      return lines.join('\n')
    },
    tools: [
      {
        type: 'function',
        function: {
          name: 'read_document',
          description: 'Read the content of an uploaded file (JSON, CSV, TXT, etc.) by file_id.',
          parameters: {
            type: 'object',
            properties: { file_id: { type: 'string', description: 'File ID of the uploaded document.' } },
            required: ['file_id']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'run_command',
          description: 'Run a terminal command (e.g. to read a file). User must confirm. Use type path (Windows) or cat path (Unix).',
          parameters: {
            type: 'object',
            properties: { command: { type: 'string', description: 'Shell command to run.' } },
            required: ['command']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'execute_python',
          description: 'Run Python code in a sandbox. Use for data analysis, math, or generating charts. No network access.',
          parameters: {
            type: 'object',
            properties: { code: { type: 'string', description: 'Python code to execute.' } },
            required: ['code']
          }
        }
      }
    ]
  },
  {
    id: 'web',
    name: 'Web Researcher',
    description: 'Search the web and cite sources',
    buildSystemPrompt: (baseContext, system, models, contextLength, attachedFileNames) => {
      const lines = [
        baseContext,
        '',
        'You are the Web Researcher agent. Use web_search to fetch real-time information. Cite and summarize results clearly.'
      ]
      if (attachedFileNames.length) lines.push('', `User attached: ${attachedFileNames.join(', ')}. Use read_document to read them; if it fails, use run_command (user confirms).`)
      lines.push('', 'Use BUTTONS: Yes, No at the end of a message to show reply buttons.')
      return lines.join('\n')
    },
    tools: [
      {
        type: 'function',
        function: {
          name: 'web_search',
          description: 'Search the web for real-time information. Returns snippets and summaries.',
          parameters: {
            type: 'object',
            properties: { query: { type: 'string', description: 'Search query.' } },
            required: ['query']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'read_document',
          description: 'Read an uploaded file by file_id (JSON, TXT, etc.).',
          parameters: {
            type: 'object',
            properties: { file_id: { type: 'string', description: 'File ID.' } },
            required: ['file_id']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'run_command',
          description: 'Run a terminal command (e.g. read a file). User must confirm.',
          parameters: {
            type: 'object',
            properties: { command: { type: 'string', description: 'Shell command.' } },
            required: ['command']
          }
        }
      }
    ]
  },
  {
    id: 'coding',
    name: 'Coding Expert',
    description: 'Code generation, scripts, and debugging',
    buildSystemPrompt: (baseContext, system, models, contextLength, attachedFileNames) => {
      const lines = [
        baseContext,
        '',
        'You are the Coding Expert agent. Help with code generation, debugging, and scripts. Use execute_python to run or demonstrate code. Prefer clear, runnable snippets. After every tool run (e.g. execute_python), always reply with a short follow-up: show the result, the next step, or the actual code you promised—do not leave the user with no message after a tool runs.'
      ]
      if (attachedFileNames.length) lines.push('', `Attached: ${attachedFileNames.join(', ')}. Use read_document to read file contents; if it fails, use run_command (user confirms).`)
      lines.push('', 'Use BUTTONS: label1, label2 at the end of a message to show reply buttons.')
      return lines.join('\n')
    },
    tools: [
      {
        type: 'function',
        function: {
          name: 'read_document',
          description: 'Read an uploaded file by file_id (JSON, code, etc.).',
          parameters: {
            type: 'object',
            properties: { file_id: { type: 'string', description: 'File ID.' } },
            required: ['file_id']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'run_command',
          description: 'Run a terminal command (e.g. read a file). User must confirm.',
          parameters: {
            type: 'object',
            properties: { command: { type: 'string', description: 'Shell command.' } },
            required: ['command']
          }
        }
      },
      {
        type: 'function',
        function: {
          name: 'execute_python',
          description: 'Execute Python code in a sandbox. Use for demos or small scripts.',
          parameters: {
            type: 'object',
            properties: { code: { type: 'string', description: 'Python code.' } },
            required: ['code']
          }
        }
      }
    ]
  }
]
